---
- name: Idena Node Management
  hosts: main
  become: yes

  tasks:
    - name: Check if idena node daemon is run
      ansible.builtin.service_facts:
      tags: always

    # Mining Management: ON/OFF
    - name: Mining ON
      block:
        - name: dna_becomeOnline
          ansible.builtin.uri:
            url: http://{{ httphost }}:{{ httpport }}
            method: POST
            headers:
              Content-Type: application/json
            body_format: json
            body:
              jsonrpc: "2.0"
              key: "{{ vault_api_key }}"
              id: 1
              method: "dna_becomeOnline"
              params:
                - {}
            return_content: yes
          register: responseMiningOn

        - name: stdout of dna_becomeOnline to variable
          debug:
            var: responseMiningOn.content
      tags: [never, IdenaMiningOn]
      when: ansible_facts.services["idena_" + username + ".service"].state == 'running'

    - name: Mining OFF
      block:
        - name: dna_becomeOffline
          ansible.builtin.uri:
            url: http://{{ httphost }}:{{ httpport }}
            method: POST
            headers:
              Content-Type: application/json
            body_format: json
            body:
              jsonrpc: "2.0"
              key: "{{ vault_api_key }}"
              id: 1
              method: "dna_becomeOffline"
              params:
                - {}
            return_content: yes
          register: responseMiningOff

        - name: stdout of dna_becomeOffline to variable
          debug:
            var: responseMiningOff.content

      tags: [never, IdenaMiningOff]
      when: ansible_facts.services["idena_" + username + ".service"].state == 'running'

    # Node Management: ON/OFF
    - name: Start Idena Daemon
      block:
        - name: Service idena_{{ username }} start
          ansible.builtin.service:
            name: idena_{{ username }}
            state: started
          register: responseNodeStart

        - name: stdout of responseNodeStart to variable
          debug:
            var: responseNodeStart.state

      tags: [never, IdenaNodeStart]
      when: ansible_facts.services["idena_" + username + ".service"].state == 'stopped'

    - name: Stop Idena Daemon
      block:
        - name: Service idena_{{ username }} stop
          ansible.builtin.service:
            name: idena_{{ username }}
            state: stopped
          register: responseNodeStop

        - name: stdout of responseNodeStop to variable
          debug:
            var: responseNodeStop.state

      tags: [never, IdenaNodeStop]
      when: ansible_facts.services["idena_" + username + ".service"].state == 'running'
