---
- name: Idena Deployment
  hosts: main
  become: yes

  roles:
    - install_required_packages
    - disable_ssh_password
    - security_preparations
    - idena_user_add
    - idena_user_home
    - idena_daemon_add
    - ufw_rules
