---
- name: Installing requiered packages
  hosts: main
  become: true
  tasks:
    - name: Updating apt repo and cache
      apt: update_cache=yes upgrade=dist cache_valid_time=300
    - name: Checking if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Rebooting a server if required
      reboot:
      when: reboot_required_file.stat.exists == true
    - name: Install IDENA requiered packages
      apt:
        pkg:
          - jq
          - git
          - ufw
          - curl
          - wget
          - nano
          - screen
          - psmisc
          - unzip
          - netcat-traditional

- hosts: main
  roles:
    - role: disable_ssh_password
      sshd_PasswordAuthentication: "no"
  become: yes

- name: Some security preparations
  hosts: main
  become: true
  tasks:
    - name: Deploy root SSH key
      ansible.posix.authorized_key:
        user: root
        state: present
        exclusive: true
        key: "{{ lookup('file', '{{ public_key_file }}') }}"

- name: Adding a new user and creating its home directory
  hosts: main
  become: true
  tasks:
    - name: Getting a list of user groups
      getent:
        database: group
    - name: Create Idena node users' group
      group:
        name: "{{ super_group }}"
        state: present
      when: super_group not in ansible_facts.getent_group
    - name: Create Idena user
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        groups: "{{ super_group }}"
        append: yes
    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        exclusive: true
        key: "{{ lookup('file', '{{ public_key_file }}') }}"

- name: User home folder preparation
  hosts: main
  become: true
  tasks:
    - name: Checking if Idena already exists
      ansible.builtin.stat: path=/home/{{ username }}/idena-go
      register: idenago_status
    - name: Create idena-go, datadir and keystore folder
      ansible.builtin.file:
        path: /home/{{ username }}/idena-go/datadir/keystore
        state: directory
        mode: "0755"
        recurse: true
        owner: "{{ username }}"
        group: "{{ super_group }}"
      when: idenago_status.stat.exists == false
    - name: Download latest idena-go build
      ansible.builtin.get_url:
        url: https://github.com/idena-network/idena-go/releases/download/v{{ idena_go_ver }}/idena-node-linux-{{ idena_go_ver }}
        dest: /home/{{ username }}/idena-go/idena-node
        mode: "0755"
        owner: "{{ username }}"
        group: "{{ super_group }}"
      when: idenago_status.stat.exists == false
    - name: Changing perm of "idena-go", adding "+x"
      ansible.builtin.file:
        dest: /home/{{ username }}/idena-go/idena-node
        mode: a+x
        owner: "{{ username }}"
        group: "{{ super_group }}"
      when: idenago_status.stat.exists == false
    - name: Unpack latest IDENA blockchain snapshot
      ansible.builtin.git:
        repo: https://github.com/ltraveler/idenachain.db.git
        dest: /home/{{ username }}/idena-go/datadir/idenachain.db
        single_branch: yes
        version: main
        update: yes
      become: yes
      become_user: "{{ username }}"
      when: idenago_status.stat.exists == false
    - name: Template config.json to idena-go
      ansible.builtin.template:
        src: ./node/config.j2
        dest: /home/{{ username }}/idena-go/config.json
        owner: "{{ username }}"
        group: "{{ super_group }}"
        mode: "0664"
    - name: Copying api.key
      ansible.builtin.template:
        src: ./node/api.j2
        dest: /home/{{ username }}/idena-go/datadir/api.key
        owner: "{{ username }}"
        group: "{{ super_group }}"
        mode: "0664"
    - name: Copying nodekey
      ansible.builtin.template:
        src: ./node/nodekey.j2
        dest: /home/{{ username }}/idena-go/datadir/keystore/nodekey
        owner: "{{ username }}"
        group: "{{ super_group }}"
        mode: "0664"

- name: Creating Idena daemon
  hosts: main
  become: true
  tasks:
    - name: Checking if service exists
      ansible.builtin.stat: path=/etc/systemd/system/idena_{{ username }}.service
      register: service_status
    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Idena service doesn't exist"
      when: service_status.stat.exists == false
    - name: Copy idena.service
      ansible.builtin.template:
        src: ./node/idena_service.j2
        dest: /etc/systemd/system/idena_{{ username }}.service
        owner: root
        group: root
        mode: 0644
      when: service_status.stat.exists == false
      notify: daemon-reload # Don't forget to do `systemctl daemon-reload`!
  handlers:
    - name: daemon-reload
      ansible.builtin.service:
        name: idena_{{ username }}
        state: started

- name: Setting UFW rules
  hosts: main
  become: true
  tasks:
    - name: UFW +SSH connections
      community.general.ufw:
        rule: limit
        name: OpenSSH
    - name: UFW +IPFS port
      community.general.ufw:
        rule: allow
        port: "{{ ipfsport }}"
    - name: UFW enabled, deny all apart from allowed
      community.general.ufw:
        state: enabled
        default: deny

- name: Increasing some system limits
  hosts: main
  become: true
  tasks:
    - name: Add or modify nofile hard and soft limits for the idena user
      community.general.pam_limits:
        domain: "{{ username }}"
        limit_type: "-"
        limit_item: nofile
        value: "{{ pam_limits_nofile }}"
    - name: changing system.conf fs.file-max
      ansible.posix.sysctl:
        name: fs.file-max
        value: "{{ fs_filemax }}"
        state: present
    - name: systemd system.conf nofile, nproc modification
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/systemd/system.conf
        regexp: '^\s*#*\s*({{ item.param }})'
        line: '\1={{ item.value }}'
        backrefs: yes
        state: present
      with_items:
        - { param: "DefaultLimitNOFILE", value: "{{ limit_nofile_hard }}" }
        - { param: "DefaultLimitNPROC", value: "{{ limit_nproc_hard }}" }
      notify: daemon-reexec
  handlers:
    - name: daemon-reexec
      ansible.builtin.systemd:
        daemon_reexec: true
