---
- name: Idena Management
  hosts: main
  become: yes
  become_user: "{{ username }}"

  tasks:
    - name: Check if idena go is installed
      ansible.builtin.stat:
        path: /home/{{ username }}/idena-go/config.json
      register: idenanode

    - name: Check if idena-node-proxy is installed
      ansible.builtin.stat:
        path: /home/{{ username }}/idena-node-proxy/config.json
      register: idenaproxy

    - name:
      include_role:
        name: idena_api_keys_update
      when: idenanode.stat.exists and idenaproxy.stat.exists
