---
- name: Getting a list of user groups
  getent:
    database: group

- name: Create Idena node users' group
  group:
    name: "{{ idena_group }}"
    state: present
  when: idena_group not in ansible_facts.getent_group

- name: Create Idena user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    password: "{{ userpass | password_hash('sha512') }}"
    update_password: on_create
    groups: "{{ idena_group }}"
    append: yes

- name: Deploy SSH Public Key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    exclusive: true
    key: "{{ lookup('file', '{{ public_key_file }}') }}"
