---
- name: Deploy root SSH key
  ansible.posix.authorized_key:
    user: root
    state: present
    exclusive: true
    key: "{{ lookup('file', '{{ public_key_file }}') }}"
  when: public_key_file is defined and public_key_file != ''
