---
- name: Updating apt repo and cache
  ansible.builtin.apt: update_cache=yes upgrade=dist cache_valid_time=100

- name: Install IDENA requiered packages
  ansible.builtin.apt:
    pkg: "{{ required_packages }}"

- name: Remove conflicting packages
  ansible.builtin.apt:
    name: python3-openssl
    state: absent

- name: Checking if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting a server if required
  reboot:
  when: reboot_required_file.stat.exists == true

- name: Installing required python packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    extra_args: "{{ '--upgrade' if pip_packages is defined and 'pyOpenSSL' in pip_packages else '' }}"
  vars:
    pip_packages:
      - pyOpenSSL
      - pexpect
      - github3.py
  become: yes
